robot:
  id: "qyh-robot-001"
  name: "QYH Robot"

signaling:
  server_url: "http://127.0.0.1:8000/api/v1/signaling"
  robot_secret: "qyh-robot-secret"

webrtc:
  ice_servers:
    - urls: "stun:stun.l.google.com:19302"

ros2:
  cmd_vel_topic: "/cmd_vel"
  manual_velocity_topic: "/manual_velocity_cmd"
  manual_motion_topic: "/manual_motion_cmd"
  joint_command_topic: "/joint_command"
  gripper_command_topic_prefix: "/gripper/command"
  joint_state_topic: "/joint_states"
  imu_topic: "/imu"
  odom_topic: "/odom"
  standard_robot_status_topic: "standard_robot_status"
  navigation_status_topic: "navigation_status"
  arm_state_topic: "/jaka/robot_state"
  head_joint_state_topic: "/head/joint_states"
  lift_state_topic: "/lift/state"
  waist_state_topic: "/waist/state"
  left_gripper_state_topic: "/left/gripper_state"
  right_gripper_state_topic: "/right/gripper_state"
  head_command_topic: "/head_motor_node/cmd_position"
  lift_control_service: "/lift/control"
  waist_control_service: "/waist/control"
  left_gripper_activate_service: "/left/activate_gripper"
  left_gripper_move_service: "/left/move_gripper"
  right_gripper_activate_service: "/right/activate_gripper"
  right_gripper_move_service: "/right/move_gripper"
  arm_movej_service: "/jaka/move_j"
  arm_movel_service: "/jaka/move_l"
  arm_jog_service: "/jaka/jog"
  arm_jog_stop_service: "/jaka/jog_stop"
  nav_to_coordinate_service: "/go/navigate_to_coordinate"
  nav_to_site_service: "/go/execute_action_task"
  nav_to_site_task_service: "/go/navigate_to_site_with_task"
  nav_pause_service: "/control/pause_move"
  nav_resume_service: "/control/resume_move"
  nav_cancel_service: "/control/stop_move"
  chassis_emergency_stop_service: "/control/emergency_stop"
  chassis_release_emergency_service: "/control/release_emergency_stop"
  chassis_start_charging_service: "/control/start_charging"
  chassis_stop_charging_service: "/control/stop_charging"
  chassis_enter_low_power_service: "/control/enter_low_power_mode"
  chassis_exit_low_power_service: "/control/exit_low_power_mode"
  chassis_start_manual_service: "/control/start_manual_control"
  chassis_stop_manual_service: "/control/stop_manual_control"
  chassis_pause_mission_service: "/control/pause_mission"
  chassis_resume_mission_service: "/control/resume_mission"
  chassis_cancel_mission_service: "/control/cancel_mission"
  chassis_stop_localization_service: "/control/stop_localization"
  chassis_system_reset_service: "/control/system_reset"
  task_execute_service: "/task_engine/execute"
  task_pause_service: "/task_engine/pause"
  task_resume_service: "/task_engine/resume"
  task_cancel_service: "/task_engine/cancel"
  task_status_topic: "/task_engine/status"
  led_color_topic: "/robot_led/set_color"
  led_blink_topic: "/robot_led/blink"
  shutdown_service: "/shutdown"
  shutdown_state_topic: "/shutdown_state"
  vr_head_pose_topic: "/vr/head/pose"
  vr_left_active_topic: "/vr/left_controller/active"
  vr_right_active_topic: "/vr/right_controller/active"
  vr_left_pose_topic: "/vr/left_controller/pose"
  vr_right_pose_topic: "/vr/right_controller/pose"
  vr_left_joy_topic: "/vr/left_controller/joy"
  vr_right_joy_topic: "/vr/right_controller/joy"

media:
  encoding: "h265"
  cameras:
    - name: "head"
      color_topic: "/head_camera/color/image_raw"
      depth_topic: "/head_camera/depth/image_raw"
      width: 1280
      height: 720
      fps: 0
    - name: "left"
      color_topic: "/left_camera/color/image_raw"
      depth_topic: "/left_camera/depth/image_raw"
      width: 1280
      height: 720
      fps: 0
    - name: "right"
      color_topic: "/right_camera/color/image_raw"
      depth_topic: "/right_camera/depth/image_raw"
      width: 1280
      height: 720
      fps: 0
